### ISSUE TITLE
Adding Expected Data breaks some monitors

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/citizen-onboard#33]
- www.mybenefitscalwin.org
- www.marylandsail.org/Application/Default.aspx
- https://epass.nc.gov/CitizenPortal/application.do
### MBCW details

![screen shot 2015-01-18 at 3 02 45 pm](https://cloud.githubusercontent.com/assets/2533112/5794464/1a8763fc-9f23-11e4-936d-410b12fd21f8.png)
![screen shot 2015-01-18 at 3 02 12 pm](https://cloud.githubusercontent.com/assets/2533112/5794465/1a88f56e-9f23-11e4-8c56-6eba09423e38.png)

But it says it's down :(

**Comment by pingometer** [comment]
# MBCW

It looks like there is code on the page that gives this message to our system:

`The Web Browser you are using is not supported by MyBenefits CalWIN. Below is a list of supported browsers. Please select Contact Us from the top of the page to contact your County if you have any issues.`

Since `Username` is not in the response body, it indicates the site is down.

Instead, you can use a transaction monitor which emulates a real browser.

For "Commands", use this:

`{
    "1": {
        "get": "https://www.marylandsail.org/Application/Default.aspx"
    },
    "2": {
        "assert_in_content": "Application"
    }
}`

# Maryland Sail

It looks like there is code on the page that gives this message to our system:

`Browser is not supported !!!`

Instead, you can use a transaction monitor which emulates a real browser.

For "Commands", use this:

`{
    "1": {
        "get": "https://www.mybenefitscalwin.org"
    },
    "2": {
        "assert_in_content": "Username"
    }
}`

# ePASS

It looks like there is a client-side (JavaScript) redirect that doesn't get executed; we only follow server-side redirects:

`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">\n  <html><head><script type="text/javascript">\n        function autoSubmit() {\n          document.getElementById("loginform").submit();\n        }\n      </script><noscript><META CONTENT="0;URL=nojavascript.jsp" HTTP-EQUIV="Refresh"/></noscript><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/><style type="text/css">\n\t  \tbody {font:13px/1.231 arial,helvetica,clean,sans-serif;*font-size:small;*font:x-small;}\n\n\t\t#home-page-panel {\n  \t\tbackground-repeat: no-repeat;\n  \t\tbackground-image: url("http://www.ncdhhs.gov/ncfast/images/NC_front_panel_mid.png");\n  \t\theight: 300px;\n\t\t}\n\n\t\t#welcome-text-1 {\n  \t\tmargin-left: 15px;\n  \t\tpadding-top: 20px;\n  \t\twidth: 400px;\n  \t\tcolor: #3276ad;\n  \t\tfont-size: 182%;\n\t\t}\n\n\t\t#welcome-text-2 {\n  \t\tmargin-left: 15px;\n  \t\tmargin-top: 5px;\n  \t\twidth: 400px;\n  \t\tcolor: #000000;\n  \t\tfont-size: 100%;\n\t\t}\n\n\t\ta.nc-footer {\n\t\tcolor: #E36117;\n\t\tfont-size:11px;\n\t\ttext-decoration: none;\n\t\t}\n\n\t\ta.nc-footer:hover {\n\t\ttext-decoration: underline;\n        \t}\n\n        \tdiv.cluster h3.desc-header div.nc-footer {\n\t\ttext-align: center;\n        \t}\n\t\t</style></head><body class="logonBody" onload="autoSubmit()" style="visibility: visible;"><form action="j_security_check" id="loginform" method="post" name="loginform"><input name="j_username" type="hidden" value="publiccitizen"/><input name="j_password" type="hidden" value="password"/><input name="user_type" type="hidden" value="EXT_AUTO"/><input id="redirectRequired" name="redirectRequired" type="hidden" value="true"/></form><script type="text/javascript">\n      /*\n      * This javascript will always get executed. \n      * Either a redirect will be invoked or a the login will be submitted.\n      */ \n      var redirectRequired = document.getElementById("redirectRequired").value;\n      \n      if(redirectRequired) {\n        if(window.top!=window.self) {\n          // iframe\n          window.top.location.href="/CitizenPortal/application.do";          \n        }\n        else {\n          // no iframe\n          window.location.href="/CitizenPortal/application.do";\n        }\n      }\n      else {\n        document.getElementById("loginform").submit();            \n      }\n            \n\t</script></body></html>`

Instead, you can use a transaction monitor which emulates a real browser (and would allow the client-side redirect).

For "Commands", use this:

`{
    "1": {
        "get": "https://epass.nc.gov/CitizenPortal/application.do"
    },
    "2": {
        "assert_in_content": "Apply"
    }
}`

## 

Let me know if you have any questions.

**Comment by lippytak** [comment]
:+1: thanks a ton @pingometer ! Looks like these three are all working as expected now.
